# Generated by Django 2.2.6 on 2020-12-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201209_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите текст комментария', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(help_text='Введите свой комментарий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='posts.Comment', verbose_name='Комментарий'),
        ),
    ]
